一、axis使用教程:

sum/mean/max/argmax 这类“聚合/归约”函数：消掉axis  
对于二维矩阵而言：axis=0就是对列进行处理；axis=1就是对行进行处理

np.concatenate(arrays, axis=k)：在第 k 维把长度加起来(其它维度必须相同)

np.stack(arrays, axis=k)：多出一维，axis 指新维插在第几维位置(形状必须相同)

<img src="pics/2.png" width="35%" />

In [1]:

import numpy as np

array_23=np.array([[1,3,4],[2,4,5]])
array_22=np.array([[10,30],[20,40]])
print(array_23.shape,array_23)
print(array_22.shape,array_22)
axis_1=np.sum(array_23,axis=1)
print("sum",axis_1.shape,axis_1)

axis_1=np.argmax(array_23,axis=1)
print("argmax",axis_1.shape,axis_1)

axis_1=np.concatenate([array_23,array_22],axis=1)
print("concatenate",axis_1.shape,axis_1)

array_23_0=np.array([[10,30,40],[20,40,50]])
axis_1=np.stack([array_23,array_23_0,array_23,array_23_0],axis=1)
print("stack",axis_1.shape,axis_1)


(2, 3) [[1 3 4]
 [2 4 5]]
(2, 2) [[10 30]
 [20 40]]
sum (2,) [ 8 11]
argmax (2,) [2 2]
concatenate (2, 5) [[ 1  3  4 10 30]
 [ 2  4  5 20 40]]
stack (2, 4, 3) [[[ 1  3  4]
  [10 30 40]
  [ 1  3  4]
  [10 30 40]]

 [[ 2  4  5]
  [20 40 50]
  [ 2  4  5]
  [20 40 50]]]


In [2]:

import numpy as np

array_423=np.array([[[1,3,4],[2,4,5]],[[12,33,42],[22,41,52]],[[221,223,334],[222,224,335]],[[2221,1113,1114],[1112,1114,1115]]])
print(array_423)
print(array_423.shape)
axis_1=np.sum(array_423,axis=1)
print("sum",axis_1.shape,axis_1)

axis_1=np.argmax(array_423,axis=1)
print("argmax",axis_1.shape,axis_1)

axis_1=np.concatenate([array_423],axis=1)
print("concatenate",axis_1.shape,axis_1)


[[[   1    3    4]
  [   2    4    5]]

 [[  12   33   42]
  [  22   41   52]]

 [[ 221  223  334]
  [ 222  224  335]]

 [[2221 1113 1114]
  [1112 1114 1115]]]
(4, 2, 3)
sum (4, 3) [[   3    7    9]
 [  34   74   94]
 [ 443  447  669]
 [3333 2227 2229]]
argmax (4, 3) [[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 1 1]]
concatenate (4, 2, 3) [[[   1    3    4]
  [   2    4    5]]

 [[  12   33   42]
  [  22   41   52]]

 [[ 221  223  334]
  [ 222  224  335]]

 [[2221 1113 1114]
  [1112 1114 1115]]]


二、交叉熵损失函数

1、交叉熵的定义：
$H(p,g)=\sum_{i}p_i\times log q_i$  
其中p为真实分布，q为模型分布，−logq去惩罚“真实应该高概率的部分”（模型分布越好，logq越高，-logq越低）  
2、简易Softmax-with-Loss计算图  
<img src="pics/3.png" width="65%" />  
设$logits=a=(a_1,a_2,a_3),softmax(a)=y=(y_1,y_2,y_3)$  
可求出$\frac{\partial L}{\partial a_i}= y_i-t_i$

三、虚拟环境构建步骤

0.使用镜像：-i https://pypi.tuna.tsinghua.edu.cn/simple  
1.conda create -n torch_env python=3.10 -y(torch_env是name)  